language: "en"

pipeline:
  - name: WhitespaceTokenizer
    intent_split_symbol: "_"
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
  - name: EmbeddingIntentClassifier
  - name: ResponseSelector  
    retrieval_intent: faq  

policies:
  - name: MemoizationPolicy
  - name: SklearnPolicy 
  - name: FallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_action_name: "actions_tidak_mengerti"  
  - name: FormPolicy
  - name: MappingPolicy